-- MySQL Script generated by MySQL Workbench
-- qua 27 nov 2019 09:08:56 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`data` (
  `iddata` INT NOT NULL,
  `dia` INT NULL,
  `mes` INT NULL,
  `ano` INT NULL,
  `diaSemana` VARCHAR(45) NULL,
  `trimestre` VARCHAR(45) NULL,
  PRIMARY KEY (`iddata`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL,
  `nomecompleto` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `endereco1` VARCHAR(45) NULL,
  `endereco2` VARCHAR(45) NULL,
  `distrito` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `codigopostal` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filme` (
  `idfilme` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `release_year` VARCHAR(45) NULL,
  `duracao` VARCHAR(45) NULL,
  `classificacao` VARCHAR(45) NULL,
  `diaria` VARCHAR(45) NULL,
  PRIMARY KEY (`idfilme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`linguagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`linguagem` (
  `idlinguagem` INT NOT NULL,
  `nomelinguagem` VARCHAR(45) NULL,
  PRIMARY KEY (`idlinguagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `idfuncionario` INT NOT NULL,
  `nomecompleto` VARCHAR(45) NULL,
  `gerenteSN` TINYINT(1) NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loja` (
  `idloja` INT NOT NULL,
  `gerente` VARCHAR(45) NULL,
  `endereco1` VARCHAR(45) NULL,
  `endereco2` VARCHAR(45) NULL,
  `distrito` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `codigopostal` VARCHAR(45) NULL,
  PRIMARY KEY (`idloja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluguel` (
  `idaluguel` INT NOT NULL,
  `data_iddata` INT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `filme_idfilme` INT NOT NULL,
  `linguagem_idlinguagem` INT NOT NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  `loja_idloja` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  `duracao` VARCHAR(45) NULL,
  PRIMARY KEY (`idaluguel`, `data_iddata`, `cliente_idcliente`, `filme_idfilme`, `linguagem_idlinguagem`, `funcionario_idfuncionario`, `loja_idloja`),
  INDEX `fk_aluguel_data_idx` (`data_iddata` ASC),
  INDEX `fk_aluguel_cliente1_idx` (`cliente_idcliente` ASC),
  INDEX `fk_aluguel_filme1_idx` (`filme_idfilme` ASC),
  INDEX `fk_aluguel_linguagem1_idx` (`linguagem_idlinguagem` ASC),
  INDEX `fk_aluguel_funcionario1_idx` (`funcionario_idfuncionario` ASC),
  INDEX `fk_aluguel_loja1_idx` (`loja_idloja` ASC),
  CONSTRAINT `fk_aluguel_data`
    FOREIGN KEY (`data_iddata`)
    REFERENCES `mydb`.`data` (`iddata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_filme1`
    FOREIGN KEY (`filme_idfilme`)
    REFERENCES `mydb`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_linguagem1`
    FOREIGN KEY (`linguagem_idlinguagem`)
    REFERENCES `mydb`.`linguagem` (`idlinguagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `mydb`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_loja1`
    FOREIGN KEY (`loja_idloja`)
    REFERENCES `mydb`.`loja` (`idloja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
